jobs:
  build-test:
    working_directory: ~/linear-algebra
    docker:
        - image: circleci/python:3.6.10
    resource_class: small
    steps:
        - checkout
        - restore_cache:
            key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
        - run:
            name: Install Python deps in a venv
            command: |
                python3 -m venv venv
                source ./venv/bin/activate
                pip install .
        - save_cache:
            key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
            paths:
                - "./venv"
        - run:
            name: test
            command: |
                source ./venv/bin/activate
                pytest tests

  deploy:
    working_directory: ~/linear-algebra
    docker:
        - image: circleci/python:3.6.10
    resource_class: small
    steps:
        - add_ssh_keys:
            fingerprints:
                - "21:a6:81:44:96:78:3a:a4:88:89:7f:43:ac:b7:ab:69"
        - run:
            name: Avoid hosts unknown for github
            command: echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        - run:
            name: "create-repo"
            command: |
                git config --global user.name "srcolinas-machine-user"
                git config --global user.email "srcolinas+machine@gmail.com"
                ls -la
                git clone https://github.com/open-workbooks/linear-algebra.git
                ls -la
                cd linear-algebra
                ls -la
                cat README.md
                echo "# linear-algebra-test3" >> README.md
                cat RAEDME.md
                git add README.md
                git commit -m "deployment test"
                git push          

workflows:
    version: 2
    build-test-deploy:
        jobs:
            - build-test:
                filters:
                    branches:
                        only: master
            - hold:
                type: approval
                requires:
                    - build-test
            - deploy:
                requires:
                    - hold
