version: 2.1

jobs:
  build:
    working_directory: ~/linear-algebra
    docker:
        - image: circleci/python:3.6.10
    steps:
        - checkout
        - run: sudo chown -R circleci:circleci /usr/local/bin
        - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
        - restore_cache:
            key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
        - run:
            command: |
                python3 -m venv venv
                source ./venv/bin/activate
                pip install .
            name: Install Python deps in a venv
        - save_cache:
            key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
            paths:
                - "./venv"
        - run:
            command: |
                source ./venv/bin/activate
                pytest -n 2 tests
            name: activate environment and run test
        - store_test_results:
            path: test-results
        - store_artifacts:
            path: test-results
            destination: tr1
      