version: 2.1

jobs:
  build:
    working_directory: ~/linear-algebra
    docker:
        - image: circleci/python:3.6.10
    resource_class: small
    steps:
        - checkout
        - restore_cache:
            key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
        - run:
            command: |
                python3 -m venv venv
                source ./venv/bin/activate
                pip install .
            name: Install Python deps in a venv
        - save_cache:
            key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
            paths:
                - "./venv"
        - run:
            command: |
                source ./venv/bin/activate
                pytest tests
            name: test
