# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish workbook

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.PUSH_TO_PUBLIC_REPOS }}
    - name: build and push
      run: |
        ls -la
        git config --global user.name "srcolinas-machine-user"
        git config --global user.email "srcolinas+machine@gmail.com"
        git clone https://github.com/open-workbooks/linear-algebra.git
        ls -la
        cd linear-algebra
        ls -la
        cat README.md
        echo "# linear-algebra-actions" >> README.md
        cat README.md
        git add README.md
        git commit -m "deploy"
        git push